### ISSUE TITLE
Option to simulate realistic paper drafts (hide picks)

### ISSUE THREAD

**Issue by tooomm** [Senryoku/Draftmancer#385]
- New `Hide picks` setting which hides deck and sideboard views for players (also spectators?) until pack is completely drafted
- New review period in between packs needed with access to deck/sideboard and stats (with customizable time? defaulting to ~30s?)

This would require players to remember their picks to keep track of colours, curve and creature count etc. during the process.
The idea is to bring a more realistic paper draft experience to MTGADraft that allows to simulate in-store events and also prepare for more competitive tournaments for example.

**Comment by NerdyNathan** [comment]
To simplify this feature, how about just a client side option to hide/show picks as desired? The option to hide picks sounds like a personal choice, especially since it's impossible to enforce users not taking notes if they really want track picks.

**Comment by tooomm** [comment]
That's a reasonable first step and a nice feature, sure!

But it doesn't solve the request in my opinion.
There is a difference between having cheating enabled by default (current status), enable cheating with one click (your suggestion), or require effort and external tools or paper to record your picks.

Of course you can not prevent people from taking notes, but you can make it reasonably hard and time consuming (very scarce resource in a competitively timed draft!) instead having it build in. Utilising such notes **during the draft** is also more costly than having them perfectly and nicely presented and sorted for players to use. 

Time is really an issue in a competitive setting. Default timing for Draftmancer is 75s for example, in a tournament it's only 40s:

> **Booster Draft Timing**
Individual booster drafts have the following default time limits for each pick:
>
>Cards remaining / Time allotted
15 cards	40 seconds
14 cards	40 seconds
13 cards	35 seconds
12 cards	30 seconds
11 cards	25 seconds
10 cards	25 seconds
9 cards	   20 seconds
8 cards	   20 seconds
7 cards	   15 seconds
6 cards	   10 seconds
5 cards	   10 seconds
4 cards	    5 seconds
3 cards	    5 seconds
2 cards	    5 seconds
1 card	          N/A
>
>The time for review after the first booster pack is 60 seconds. Each subsequent review period increases by 30 seconds.
>
>Source: https://blogs.magicjudges.org/rules/mtr-appendix-b/

**Comment by Senryoku** [comment]
I think I'd rather do both at the same time, I'm not sure there's a lot of benefits in implementing a client-side only solution as one key difference is the additional review time between packs (which needs to be handled server-side anyway).
There's also the question of the allotted time per pick. If we start to implement these kind of options for tournaments, we should probably consider supporting the official rules described by @tooomm.

I'm focusing on other things for now (mainly the two opened PRs) and might even make some changes to the way timers are managed for #457, so I'd like to be completely done with this one before considering adding this option.

**Comment by Senryoku** [comment]
I have a working prototype in #494, it adds the following settings:

![image](https://github.com/Senryoku/Draftmancer/assets/1338143/dd6de39e-b61f-4009-a640-e5dc2ddaa204)

You can try it out there:  http://beta.draftmancer.com
