### ISSUE TITLE
Option to remove basics from card pool

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/Draftmancer#430]
In some game mode (e.g. Housman, Solomon...), keeping basics when drafting from standard sets doesn't make a lot of sense and feels bad when drafting. They are automatically omitted when possible, but not when the set has some other possible lands in its land slot.

Add an option (enabled by default?) in their respective dialog to remove basics from the card pool after it has been generated. Generate more packs (by reducing their expected size by one) to make sure we generate enough cards.

**Comment by NerdyNathan** [comment]
@Senryoku are you taking contributions? I think I could work on this. Thanks for all the great work!

**Comment by Senryoku** [comment]
> @Senryoku are you taking contributions? I think I could work on this. Thanks for all the great work!


I do, thanks for asking!
In this case I merely opened this issue as a note to myself because I couldn't tackle it immediately. It shouldn't take me too long to implement once I have time to work on it, but feel free to look around if you're interested :)

**Comment by NerdyNathan** [comment]
Sounds good, I'll poke around

**Comment by NerdyNathan** [comment]
I think I've got it working locally for Solomon draft. For which draft modes did you want this option? I expect at least these:
- Solomon
- Winston
- Winchester
- Housman
- Grid

**Comment by Senryoku** [comment]
I don't have a list, but yours looks good!
