### ISSUE TITLE
Differentiate symbol for flipping and rotating DFC Battles

### ISSUE THREAD

**Issue by NerdyNathan** [Senryoku/Draftmancer#449]
Currently, the mouse-over symbol for rotating a Battle 90 degrees is two arrows in a circle, and the symbol for flipping to see the back of a DFC Battle are slightly squished two arrows in a circle.

Maybe something that resembles the Tap symbol for rotation?

**Comment by Senryoku** [comment]
True, especially now with battles that can have both symbols, better differentiating them would be great.

Fontawesome has these two if we want to keep it consistent:
![image](https://user-images.githubusercontent.com/1338143/235788678-40379a61-828f-4258-ab2a-862560c0213b.png)
But using the tap symbol would be flavorful. Maybe we could also update the flip symbol to try to have both the flavor and the consistency.

**Comment by NerdyNathan** [comment]
Nice, I can work on this after I finish up #430 in the next day or two, if you like.

**Comment by Senryoku** [comment]
Experimenting with a tab symbol:
![image](https://user-images.githubusercontent.com/1338143/235902226-b70f90a2-9b35-48ba-9f06-8a2ca1d75261.png)

**Comment by Senryoku** [comment]
93b2c7c33ff10586453a6525c254b8f6770d06e7
