### ISSUE TITLE
feature request: pick X sets

### ISSUE THREAD

**Issue by fluidvanadium** [Senryoku/Draftmancer#488]
in the draft weer trying to play, we have 3 players and 7 rounds. in <random set from card pool> mode, 21 sets are picked from a pool of 147 and then randomly distributed. could we pick 7 sets and give a pack of each to each player? then, shuffle the packs so that each round contains different sets from the smaller pool

**Comment by Senryoku** [comment]
Add option [Random set from Card Pool (Shared)](https://github.com/Senryoku/Draftmancer/commit/bfbbcfd36c691ee87c00c42ffb2bd38043d3e561)

**Comment by fluidvanadium** [comment]
thank you!
