### ISSUE TITLE
Reset icon over default quantity text

### ISSUE THREAD

**Issue by tooomm** [Senryoku/Draftmancer#521]
I suggest to use something like a reset icon, instead writing what the default amount of busters is. The value is probably not often changed to begin with, it also resets to the default value on reload/reopen already.
- actively help the user to set the number to the most common value
- fewer permanent text in UI with little use
- cleaner interface

The icon can also be only visible if the value is changed from defaults.

This is similar in most create games dialogs when selecting and setting up the game type. I picked sealed as an example here:
![image](https://github.com/Senryoku/Draftmancer/assets/9874850/897049bb-4913-4dca-8f00-f05ef0498322)

Mockup of a potential solution:
![image](https://github.com/Senryoku/Draftmancer/assets/9874850/f9b2038a-6160-4fa1-ae15-06b42389124c)
The circle being a placeholder here for a reset icon - e.g. a single, circular arrow. A hint could further help and clarify the action `Reset to default value`

**Comment by Senryoku** [comment]
Make sense, implemented in 7ef3867
![image](https://github.com/Senryoku/Draftmancer/assets/1338143/473bb9bf-1823-4237-8406-9a3d0d408d5a)

**Comment by tooomm** [comment]
Cool, the result for the Sealed dialogs is looking good!

This is not only about sealed though. The various draft dialogs would benefit from this as well. :)
Winston, Winchester, Grid, Glimpse

<br>

Is there a reason the field for the booster quantity is that big btw?

**Comment by Senryoku** [comment]
> Cool, the result for the Sealed dialogs is looking good!
> 
> This is not only about sealed though. The various draft dialogs would benefit from this as well. :) Winston, Winchester, Grid, Glimpse

Mmh, yes, obviously, I knew it when I first read your issue, but it somehow completely eluded me when I sat down to fix it xD 
I don't think I'll update all them (some of these dialogs use sweetalert and aren't easily customizable), but I'll review them one by one.

> Is there a reason the field for the booster quantity is that big btw?

Not really, but now that I look at them the dialogs are all over the place. I'll probably tweak all the styles while I'm there.

**Comment by Senryoku** [comment]
58209c8 adds a couple more reset buttons.
For the rest, see #541 (they're all sweetalerts)
