### ISSUE TITLE
Jumpstart pack selection not fully shown

### ISSUE THREAD

**Issue by tooomm** [Senryoku/Draftmancer#537]
Not all packs are properly shown in the dialog and stay partially covered even when scrolling to the sides.
This applies to Jumpstart Historic Horizons & Superjump pack selection.

There is also no `Cancel` button to go back.

**Comment by Senryoku** [comment]
5fae434 should help.

I don't think a cancel button is necessary here. If you had a deck it's already gone anyway, and it's at most two more clicks to end the event.

**Comment by Senryoku** [comment]
Alright, 89ed685 should help in this case (display will change only after the first pick is made, and the pack selection popup has a cancel button).

**Comment by tooomm** [comment]
I'm very much looking forward to all your recent tweaks and testing them live!

**Comment by Senryoku** [comment]
> I'm very much looking forward to all your recent tweaks and testing them live!

I just deployed them on the beta server (http://beta.draftmancer.com) if you have some feedback before they go live :)

**Comment by tooomm** [comment]
I tested it on different screens, and it's now correctly displaying all packs from the selection! 👍 

<br>

>Alright, https://github.com/Senryoku/Draftmancer/commit/89ed685efef2137ac69a88cc494368256c1e324d should help in this case (display will change only after the first pick is made, and the pack selection popup has a cancel button).

Two notes still:
- The cancel button is grey and not red as all other cancel buttons
- I would prefer if hitting cancel after the first picked Jumpstart booster would bring you back to the start (aka cancel all game selection, and not stop in the middle and leave the user with a half selected deck in deckbuilding mode).
Can you change the display only after the last selection is done maybe?

**Comment by Senryoku** [comment]
Just tried a red cancel button, I find it too distracting: It shouldn't be your focal point in this case. I think the grey one is just fine here, even if it's not entirely consistent with the rest of the app.

I kinda agree with your second point and went back and forth between the two solutions... 179e77ae9f032f847b49ffbce14d168348d8b9ee delays any state change after both selections, cancelling at any point should now work as expected.

**Comment by tooomm** [comment]
>Just tried a red cancel button, I find it too distracting:

Fair enough, thanks for checking again.

>https://github.com/Senryoku/Draftmancer/commit/179e77ae9f032f847b49ffbce14d168348d8b9ee delays any state change after both selections, cancelling at any point should now work as expected.

👌
