### ISSUE TITLE
Wrong font for button labels in several start game dialogs

### ISSUE THREAD

**Issue by tooomm** [Senryoku/Draftmancer#539]
- Dialog with normal font:
   <img width="465" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/e6353a1b-5fb8-439a-8f5d-ecd7952189b7">

 - Dialog with wrong font:
   <img width="761" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/2ffefacb-63e7-476b-868c-d090320eb6d6">
   <img width="752" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/00b9ed19-2f1b-4d23-ac44-b92adc80ae8c">

**Comment by Senryoku** [comment]
See  #541
