### ISSUE TITLE
Booster generated with duplicate in the same slot 

### ISSUE THREAD

**Issue by Susucre** [Senryoku/Draftmancer#544]
Hello!

We did a draft with this custom remastered set a few hours ago, It had layout and slots defined and is set with `withReplacement:true`, but all cards are in x1 in their slot (and in total):
[ZRWK_draftmancer_showslots.txt](https://github.com/Senryoku/Draftmancer/files/12210188/ZRWK_draftmancer_showslots.txt)

We had some boosters generated with the same card twice, although it was not expected to be possible?
Two Pathway (in the Uncommon Slot)
![image](https://github.com/Senryoku/Draftmancer/assets/34709007/bd26e2a0-cb69-4d8c-bf39-6dad1cc65fc9)
Two Gift of Tusk (again in the Uncommon Slot):
![giftoftusk](https://github.com/Senryoku/Draftmancer/assets/34709007/b8ead916-b68e-415e-bb3f-d70dcce38898)

Here are the draft info (timezone is UTC+2) if that helps with any server logs:
![image](https://github.com/Senryoku/Draftmancer/assets/34709007/a87cdfe6-805e-4b84-9f07-22fa87010276)

**Comment by Susucre** [comment]
Just to add a more extreme custom list:
[dup_darftmancer.txt](https://github.com/Senryoku/Draftmancer/files/12213877/dup_darftmancer.txt)

This list has 7 different cards for 7 common slots, 6 for 6 uncommon slots and 5 for 5 rares slots.
I would have expected any booster to not allow for duplication, and thus have my 18 cards in every booster.
But the boosters are generated like:
![image](https://github.com/Senryoku/Draftmancer/assets/34709007/b206aa8c-6d28-493a-bbfa-d7de64f7d6b5)

**Comment by Senryoku** [comment]
Yep, I managed to introduce this bug while editing your PR.
Thanks for the bug report and test cases!
Should be fixed by 810ced146b0c4ccaebd36b67ee4f764d8f8a5a9d
