### ISSUE TITLE
Unsanitized quotation marks in .dek files break MTGO import

### ISSUE THREAD

**Issue by CapsWarlock** [Senryoku/Draftmancer#624]
"Name Sticker" Goblin, and possibly other un-cards with quotation marks in the card name, result in a .dek file that cannot be imported into MTGO because the quotation marks in the name itself are unsanitized. This appears to result in early termination of the card name field in the file. To import a file that has this card in it, you must manually edit the dek file to correct/remove the line with the card in it.

MTGO represents the `"` character in its own dek file exports as `&quot;`, so if Draftmancer also uses these replacement characters when the dek file is generated, that should result in a file that can be successfully imported into MTGO.

Draftmancer version:
` <Cards CatID="115722" Quantity="1" Sideboard="false" Name=""Name Sticker" Goblin" Annotation="0"/>`

MTGO version:
` <Cards CatID="115722" Quantity="1" Sideboard="false" Name="&quot;Name Sticker&quot; Goblin" Annotation="0" />`

**Comment by Senryoku** [comment]
Hi, thank you for the detailed report.
This should be fixed with df8b2a6, and will be part of the next update.
