### ISSUE TITLE
"Search" not working for sideboard

### ISSUE THREAD

**Issue by tooomm** [Senryoku/Draftmancer#676]
According to the helper text, it works for both main deck and sideboard:
<img width="405" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/a0fdbdf1-baf1-4c86-a391-5f02d2dbc723">

It does only work for the main deck though:
<img width="451" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/5eaa9590-fa09-48da-9b6b-e8b915a5f4d9">
<img width="450" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/2f8ae4fa-403b-431b-8dcb-515907d309b4">

**Comment by Senryoku** [comment]
Thanks for the heads up.

Fixed in 6375299d9f879f09f55ca1b6163bbf18a2929d21
![Capture d'écran 2024-03-25 002150](https://github.com/Senryoku/Draftmancer/assets/1338143/e9e3e8ac-61b2-44b0-958d-fca2c5d48a66)
