### ISSUE TITLE
Feature Suggestion - Preferred sets list.

### ISSUE THREAD

**Issue by tiera3** [Senryoku/Draftmancer#774]
It just occurred to me that being able to specify a list of preferred sets (for selecting which printing to use for a card without such information specified) would likely be useful for many cubes.

A different approach would be to allow scryfall modifiers to be specified for a first check for cards. For example, someone running an old-borders cube might use "(frame:1993 or frame:1997)" or someone preferring fancy cards might use "is:showcase". (Of course if the first check fails, a second check without the restriction should be attempted.)

**Comment by Senryoku** [comment]
Feels out-of-scope to me. This should be a feature of the software used to construct the cube, not Draftmancer imho.

(Disabling matching the exact version of cards in a cube is there to help compatibility, in case I'm missing a specific version of a card, or to ensure exportability to Arena)
