### ISSUE TITLE
MTGO export broken for MH3 DFCs

### ISSUE THREAD

**Issue by nex3** [Senryoku/Draftmancer#782]
For example, currently Fell the Profane is exported as

```xml
  <Cards CatID="126523" Quantity="1" Sideboard="false" Name="Fell the Profane // Fell Mire" Annotation="0"/>
```

where MTGO exports it as

```xml
  <Cards CatID="126521" Quantity="1" Sideboard="false" Name="Fell the Profane" Annotation="0" />
```

as a consequence, these cards are ignored when importing decks or binders.

**Comment by Senryoku** [comment]
I'm getting the MTGO IDs from Scryfall, looks like the issue comes from there (both `Fell the Profane` and `Fell the Profane // Fell Mire` import fine with the `CatID` `126521`).
I reported the issue to Scryfall. Hopefully they'll fix it quickly and I won't have to double check all MH3 MTGO IDs :D

**Comment by nex3** [comment]
Looks like this is fixed now 👍
