### ISSUE TITLE
Foil cards with sideways preview don't display properly

### ISSUE THREAD

**Issue by exoup** [Senryoku/Draftmancer#784]
If foil cards are turned on and you have a card which has a tapped preview (such as the most recent room cards), the tap preview keeps the card in the untapped state to show off the foil view.

See pictures for better explanation:

![image](https://github.com/user-attachments/assets/f76f1e5b-b70d-473b-a2f7-b17ea0273704)![image](https://github.com/user-attachments/assets/3930e781-37bf-43f4-98d7-f0f0c7c0a5ae)

**Comment by Senryoku** [comment]
Thanks for the report. This is fixed as of 4e7ffdff652986be46ddd51dc817419bc644d111 and will be live soonish :)
