### ISSUE TITLE
Bug booster generation with more boosters and fewer players

### ISSUE THREAD

**Issue by davidvlaminck** [Senryoku/Draftmancer#806]
When I use a 540 card list to create a booster draft for 8 players and 3 boosters, there is no issue.
However, when I use the same list to create a draft for 4 players with 6 boosters, I get a "Error generating boosters" message.

**Comment by Senryoku** [comment]
Can you share the list you used?

**Comment by davidvlaminck** [comment]
[draftmancer_custom.txt](https://github.com/user-attachments/files/17256740/draftmancer_custom.txt)
This is the list I used, but it was also happening when I used the Vintage cube MTGO list

At the moment I can't recreate this bug anymore. I tried all kinds of settings that I touched yesterday but a reset of the browser must have fixed it.

**Comment by Senryoku** [comment]
I wasn't able to recreate it either. This cube has just enough cards in the power slots for 24 packs, maybe there was a mistake in the number of boosters and/or players? Some bots?

Closing this for now, let me know if you manage to reproduce it.
